export const SHOPPING_PRODUCTS = [
  { id: 'fish', name: '생선', side: 'left' },
  { id: 'snack', name: '과자', side: 'left' },
  { id: 'cookie', name: '쿠키', side: 'left' },
  { id: 'shrimp', name: '새우', side: 'left' },
  { id: 'squid', name: '오징어', side: 'left' },
  { id: 'milk', name: '우유', side: 'left' },
  { id: 'juice', name: '주스', side: 'left' },
  { id: 'apple', name: '사과', side: 'both' },
  { id: 'tomato', name: '토마토', side: 'both' },
  { id: 'onion', name: '양파', side: 'both' },
  { id: 'cabbage', name: '양배추', side: 'both' },
  { id: 'carrot', name: '당근', side: 'both' },
  { id: 'grape', name: '포도', side: 'both' },
  { id: 'orange', name: '오렌지', side: 'both' },
  { id: 'banana', name: '바나나', side: 'both' },
  { id: 'book', name: '책', side: 'both' },
  { id: 'towel', name: '수건', side: 'both' },
  { id: 'pencil', name: '연필', side: 'both' },
  { id: 'scissors', name: '가위', side: 'both' },
  { id: 'note', name: '공책', side: 'both' },
  { id: 'eraser', name: '지우개', side: 'both' },
  { id: 'beef', name: '소고기', side: 'right' },
  { id: 'chicken', name: '닭고기', side: 'right' },
  { id: 'pork', name: '돼지고기', side: 'right' },
  { id: 'tissue', name: '두루마리 휴지', side: 'right' },
  { id: 'wettissue', name: '물티슈', side: 'right' },
  { id: 'kleenex', name: '각티슈', side: 'right' },
  { id: 'shampoo', name: '샴푸', side: 'right' },
] as const

export type ShoppingProductId = typeof SHOPPING_PRODUCTS[number]['id']
